[package]
name = "simula_cad"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.9" }

fj = "0.17"
fj-math = "0.17"
fj-operations = "0.17"
fj-interop = "0.17"

[dev-dependencies]
