[package]
name = "simula_mission"
version = "0.1.0"
edition = "2021"

[dependencies]
ta = "0.5"
bevy = { version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
ron = "0.7.1"

[dev-dependencies]
