[package]
name = "simula_mission"
version = "0.1.0"
edition = "2021"

[dependencies]
ta = "0.5"
bevy = { version = "0.9" }
serde = { version = "1.0", features = ["derive"] }
ron = "0.7.1"
hex = "0.4"
bevy_egui = "0.17"
bevy-inspector-egui = "0.14"

[dev-dependencies]
